notifications:
  email: false
dist: trusty
sudo: false
language: c
compiler:
  # Comment out for now to keep build matrix small
  #- clang
  - gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9
      - libedit-dev
      - libpng-dev
      - graphviz
env:
  # Configurations
  #
  # Each line in the ``env`` section represents a set of environment
  # variables passed to a build configuration
  #
  # Test a mix of llvm versions, a mix of build systems, and a mix of shared vs static library
  # Don't build as a static library with cmake. It risks exceeding the travis memory limit.
  - LLVM_VERSION=5.0.0 BUILD_SYSTEM=MAKE CXX_=g++-4.9 CC_=gcc-4.9

cache: apt

# Note the commands below are written assuming Ubuntu 12.04LTS
before_install:
  # set variables necessary for halide
  - source test/scripts/before_install_travis.sh
  # set envirnoment variables specific to this repo
  - export TEST_HALIDE_GEN=true

install:
  # install framework specific to halide
  - test/scripts/install_travis.sh  
  # compile coreir
  - git clone -b dev https://github.com/rdaly525/coreir.git
  # - make -C coreir all

script:
  # - test/scripts/build_travis.sh
  - mkdir lib
  - touch lib/libHalide.a
  - echo "hi" > lib/libHalide.a

before_deploy:
  - git config --local user.name "jeffsetter"
  - git config --local user.email "setter@stanford.edu"
  - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
  - tar -zcvf lib/libHalide.tgz lib/libHalide.a
  - echo $TRAVIS_DEPLOY_KEY > travis_key_file
  - RAW_TRAVIS_DEPLOY_KEY=`base64 --decode travis_key_file`

deploy:
  provider: releases
  api_key: $RAW_TRAVIS_DEPLOY_KEY
  file: lib/libHalie.tgz
  skip_cleanup: true
  on:
    tags: true
    
    