service: docker
language: minimal
dist: xenial

#notifications:
  #email: false
#dist: trusty
#sudo: false
#language: c
#compiler:
  #- gcc
#addons:
  #apt:
    #sources:
      #- ubuntu-toolchain-r-test
    #packages:
      ##- g++-4.9
      #- g++-7
      #- libedit-dev
      #- libpng-dev
      #- graphviz
      #- valgrind
#env:
  #- LLVM_VERSION=7.0.0 BUILD_SYSTEM=MAKE CXX_=g++-7 CC_=gcc-7

#cache: apt

# Note the commands below are written assuming Ubuntu 12.04LTS
#before_install:
  ## set variables necessary for halide
  #- source test/scripts/before_install_travis.sh
  ## set envirnoment variables specific to this repo
  #- export TEST_HALIDE_GEN=true

install:
  - docker pull keyiz/garnet-flow-cad
  - docker run -itd --memory=100m --name halide-hw-distro keyiz/garnet-flow-cad bash
  #- docker cp ../Halide-to-Hardware halide-hw-distro:/Halide-to-Hardware
  # TODO: Change this script to use travis environment variables
  - docker exec -i halide-hw-distro bash -c "git clone --branch dhuff_migrate_coreir_build_halide_from_scratch --depth 1 https://github.com/StanfordAHA/GarnetFlow.git"
  - docker exec -i halide-hw-distro bash -c "cd GarnetFlow/scripts/; ./build_halide_distrib.sh StanfordAHA/Halide-to-Hardware hls_hwbuffer_codegen_garnetflow_updates"
  - docker cp halide-hw-distro:/GarnetFlow/scripts/Halide-to-Hardware/halide_distrib.tgz ./halide_distrib.tgz
  ## install framework specific to halide
  #- test/scripts/install_travis.sh  

before_deploy:
  - git config --local user.name "jeffsetter"
  - git config --local user.email "setter@stanford.edu"
  - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
  - echo "done with travis before_deploy"
  #- make distrib
  #- rm distrib/halide.tgz
  #- rm distrib/bin/libHalide.so
  #- tar -czvf halide_distrib.tgz distrib

deploy:
  provider: releases
  api_key:
      secure: YejtxKjoEnOV0G1Dt6dPbHsrVJNNi2OZ71d9rIfs4B9ker3x0BO1EfLruNZNA1xhV8iAt1sNBzYJocuDqmCSB5j3aqlIfpkRil2HpHfQXbRtNPbwFCbhyBwVbExgXJom9GVip6+flkBMKDl7kXQg36q8f6rN9ldckp8r0SoSKVZN5kyO8NT1AKpjR+fAqzOmES6D3bvabjDWJzaFcP5WFR+ho/ISmcZwr/SpC51NUqtOvIPDlz2OYW/cMvqJrYyoJOtz9nocJuqhi26mN+i3ZMa8EUGl4MFHkiMapV4pLiOaI9OJCmj5xAjiMYUWVHAAyA2yE9jEE5nGl75qll3DQcP3LYxYfcPUlmcuBVTR0Tyx+JQ9qyLfNjGZD3PZK+s5mrN1ja9vzGv3D2Ry0HxZx+sxeoMmIWCDcRPGayhEHwBFKPj8OhCkcwYx/UJFAbnhDSmhgtU4Fq3MQJhGlK/OkP4+sm4WJvSDNdlWnFoU2CPi+mx2ht5DJpj/b55/T0t9t1eZeiAJzroMXeHvMb3/I/ro7BjIpLrfNwhHfYmyX+45RmhoiWGXnwIxy1SBVUSmxNVtdcOmxfGmig2ZR4Nb/l3GCPpyiGwfhiFvKnK2lyFoe9EBpssWbZwiDHSi9QRLK0VmSzrai2BVNE+GPld2thWZLZJEVC3OpEb+MP/ICE0=
  file: halide_distrib.tgz
  skip_cleanup: true
  on:
    tags: true
    all_branches: true

before_script:
  # create Halide compiler
  #- make -j4 distrib

script:
  - echo "at travis script"
  # run test cases for hardware codegens
  #- export HALIDE_DEBUG_REDIRECT=""
  #- bash test/scripts/build_travis.sh

after_script: |
  # See https://github.com/mernst/plume-lib/blob/master/bin/trigger-travis.sh for documentation
  echo "TRAVIS_BRANCH=$TRAVIS_BRANCH TRAVIS_PULL_REQUEST=$TRAVIS_PULL_REQUEST"
  # Is this actually required to deploy?
  if [[ ($TRAVIS_PULL_REQUEST == false) ]] ; then
    curl -LO --retry 3 https://raw.github.com/mernst/plume-lib/master/bin/trigger-travis.sh
    sh trigger-travis.sh StanfordAHA Applications $TRAVIS_ACCESS_TOKEN
  fi    
    
