name: CI Test

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    env:
       LLVM_VERSION: 6.0.0
       BUILD_SYSTEM: MAKE
       CXX_: g++-7
       CC_: gcc-7
       CXX: g++-7
       CC: gcc-7
       
       COREIR: 1
       CGRAFLOW: 1

    steps:
    - uses: actions/checkout@v2
    - name: Install packages
      run: |
          sudo apt install -y g++-7
          sudo apt install -y libedit-dev
          sudo apt install -y libpng-dev
    - name: Set environment variables
      env:
        TRAVIS_BUILD_DIR: ${{ github.workspace }}
      run: |
          echo "TRAVIS_BUILD_DIR=${{ github.workspace }}" >> $GITHUB_ENV
          echo "LLVM_CONFIG=${{TRAVIS_BUILD_DIR}}/llvm/bin/llvm-config" >> $GITHUB_ENV
          echo "CLANG=${{TRAVIS_BUILD_DIR}}/llvm/bin/clang" >> $GITHUB_ENV
          echo "COREIRCONFIG=${CXX_}" >> $GITHUB_ENV
          echo "COREIR_DIR=${{TRAVIS_BUILD_DIR}}/coreir" >> $GITHUB_ENV
          echo "COREIR_PATH=${{TRAVIS_BUILD_DIR}}/coreir" >> $GITHUB_ENV
          echo "FUNCBUF_DIR=${{TRAVIS_BUILD_DIR}}/BufferMapping/cfunc" >> $GITHUB_ENV
          echo "RDAI_DIR=${{TRAVIS_BUILD_DIR}}/rdai" >> $GITHUB_ENV
          echo "OUTPUT_REDIRECTION=\"\"" >> $GITHUB_ENV
          echo "BARVINOK_PATH=${{TRAVIS_BUILD_DIR}}/clockwork/barvinok-0.41/isl" >> $GITHUB_ENV
          echo "ISL_PATH=${{TRAVIS_BUILD_DIR}}/clockwork/barvinok-0.41/isl" >> $GITHUB_ENV
          echo "OPT_PATH=${{TRAVIS_BUILD_DIR}}/clockwork/include" >> $GITHUB_ENV
          echo "OPT_LIB_PATH=${{TRAVIS_BUILD_DIR}}/clockwork/lib" >> $GITHUB_ENV
          echo "CLKWRK_PATH=${{TRAVIS_BUILD_DIR}}/clockwork" >> $GITHUB_ENV
          echo "CLOCKWORK_DIR=${{TRAVIS_BUILD_DIR}}/clockwork" >> $GITHUB_ENV
          echo "LAKE_PATH=${{TRAVIS_BUILD_DIR}}/lake" >> $GITHUB_ENV

    - name: Install dependencies 🖥️
      shell: bash
      run: |
          test/scripts/install_travis.sh
      
          # compile coreir
          git clone -b master https://github.com/rdaly525/coreir.git
          cd coreir/build && cmake .. && make -j2 && cd ../..
          
          # compile clockwork
          git clone https://github.com/dillonhuff/clockwork.git -b aha
          cd clockwork && ./misc/install_deps_linux.sh
          make -j2 libcoreir-cgralib.so && make -j2 libclkwrk.so && cd ..
        
          # compile BufferMapping
          git clone -b new_config https://github.com/joyliu37/BufferMapping
          cd BufferMapping/cfunc && make lib -j2 && cd ../..
        
          # clone RDAI
          git clone https://github.com/thenextged/rdai.git

    - name: Install Halide
      run: make -j4 distrib

    - name: Run tests ⚙️
      shell: bash
      run: |
          export HALIDE_DEBUG_REDIRECT=""
          make -C apps/hardware_benchmarks/tests        testtravis || exit;
          make -C apps/hardware_benchmarks/apps         testtravis || exit;
          make -C apps/hardware_benchmarks/handcrafted  testtravis || exit;
          echo "Finished running tests and apps"
