name: CI Test

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    steps:
    - uses: actions/checkout@v2
    - name: Set environment variables
      run: source test/scripts/before_install_travis.sh
    - name: Install dependencies 🖥️
      shell: bash
      run: |
          test/scripts/install_travis.sh
      
          # compile coreir
          git clone -b master https://github.com/rdaly525/coreir.git
          cd coreir/build && cmake .. && make -j2 && cd ../..
          
          # compile clockwork
          git clone https://github.com/dillonhuff/clockwork.git -b aha
          cd clockwork && ./misc/install_deps_linux.sh
          make -j2 libcoreir-cgralib.so && make -j2 libclkwrk.so && cd ..
        
          # compile BufferMapping
          git clone -b new_config https://github.com/joyliu37/BufferMapping
          cd BufferMapping/cfunc && make lib -j2 && cd ../..
        
          # clone RDAI
          git clone https://github.com/thenextged/rdai.git

    - name: Install Halide
      run: make -j4 distrib

    - name: Run tests ⚙️
      shell: bash
      run: |
          export HALIDE_DEBUG_REDIRECT=""
          make -C apps/hardware_benchmarks/tests        testtravis || exit;
          make -C apps/hardware_benchmarks/apps         testtravis || exit;
          make -C apps/hardware_benchmarks/handcrafted  testtravis || exit;
          echo "Finished running tests and apps"
